5.0.0
WPChill/download-monitor pull request #1473
Opened 2024-06-18 09:05 UTC by cristianraiber

2024-07-08 13:59 UTC, cristeacosmin requested changes
e doar la prima vedere, trb sa instalez maine pe local sa vedem ce mai apare

2024-07-08 13:59 UTC, cristeacosmin commented on src/Admin/DownloadPaths/class-dlm-downloads-path-helper.php
> +		$saved_paths = self::get_all_paths();
s-ar putea ca in php 8 self:: sa fie deprecated, te rog verifica si foloseste numele clasei in loc

2024-07-08 13:59 UTC, cristeacosmin commented on src/Admin/DownloadPaths/class-dlm-downloads-path-helper.php
> +			if ( $path == $save_path['path_val'] ) {
===

2024-07-08 13:59 UTC, cristeacosmin commented on src/Admin/DownloadPaths/class-dlm-downloads-path-helper.php
> +		}
nu ai nevoie de else 
```suggestion
			$option = get_option( 'dlm_allowed_paths' );
			// Check if it's string & do combatiblility for < 5.0.0
			if ( is_string( $option ) ) {
				if ( '' != $option ) {
					// Not empty string, save as new format since 5.0.0
					$paths = array(
						array(
							'id'       => 1,
							'path_val' => $option,
							'enabled'  => true,
						),
					);
					self::save_paths( $paths );

					return $paths;
				}

				return array();
			}

			return $option;
		
```

2024-07-08 13:59 UTC, cristeacosmin commented on src/Admin/DownloadPaths/class-dlm-downloads-path-helper.php
> +	: array {
daca folosesti typeuri, foloseste peste tot. asta cred ca o sa dea erori pe minimum required php version a wordpressului ( m-am lovit la imageseo )

2024-07-08 13:59 UTC, cristeacosmin commented on src/Admin/DownloadPaths/class-dlm-downloads-path-helper.php
> +	: string {
la fel ca mai sus

2024-07-08 13:59 UTC, cristeacosmin commented on src/Admin/DownloadPaths/class-dlm-downloads-path-helper.php
> +		} else {
nici aici n-ai nevoie de else

2024-07-08 13:59 UTC, cristeacosmin commented on src/Admin/DownloadPaths/class-dlm-downloads-path-table.php
> +		$selected_view = isset( $_REQUEST['view'] ) ? sanitize_text_field( wp_unslash( $_REQUEST['view'] ) ) : 'all';
nu prea ai de ce sa sanitizezi, nu salvezi in db valoarea

2024-07-08 13:59 UTC, cristeacosmin commented on src/Admin/DownloadPaths/class-dlm-downloads-path-table.php
> +				$html .= '';
nu-i necesar

2024-07-08 13:59 UTC, cristeacosmin commented on src/Admin/DownloadPaths/class-dlm-downloads-path-table.php
> +	public function get_action_url( string $action, int $id, string $nonce_action = 'modify_approved_directories' )
verifica pe php min required version daca-ti merge

2024-07-08 13:59 UTC, cristeacosmin commented on src/Admin/DownloadPaths/class-dlm-downloads-path.php
> +			}
mult cod repetat si labartat, e f greu de citit - poate fi simplificat
```suggestion
			$site_id = get_current_blog_id();
			$uploads = WP_CONTENT_DIR . '/uploads/sites/' . $site_id;
			if ( ! empty( $_GET['id'] ) && ! empty( $_GET['page'] ) && 'download-monitor-paths' === $_GET['page'] ) {
				$site_id = absint( $_GET['id'] );
				// Create the uploads path for the site.
				$uploads = WP_CONTENT_DIR . '/uploads/sites/' . $site_id;
			} 
			$default = array(
				array(
					'id'       => 2,
					'path_val' => trailingslashit( $uploads ),
					'enabled'  => true,
				),
			);
			$args    = array(
				'type'    => 'array',
				'default' => $default,
			);

			register_setting( 'dlm_advanced_download_path', 'dlm_allowed_paths', $args );
```

2024-07-08 13:59 UTC, cristeacosmin commented on src/Admin/Extensions.php
> +		wp_send_json_success( array( 'message' => __( 'Plugin\'s license activated.', 'download-monitor' ) ) );
Uneori folosesti echo si die aici folosesti wp_send_json_success, gaseste o forma pe care sa o folosesti peste tot

2024-07-08 13:59 UTC, cristeacosmin commented on src/Admin/ExtensionsHandler.php
> +			$api_product_ids = 'dlm-captcha';
aici ai pus string, dar nu ar trebui sa fie array('dlm-captcha') ?

2024-07-08 13:59 UTC, cristeacosmin commented on src/Admin/class-dlm-admin-list-table.php
> +					'url'      => admin_url( 'edit.php?post_type=dlm_download&page=dlm-extensions' ),
nu sttiu daca are relevanta dar esc_url(

2024-07-08 13:59 UTC, cristeacosmin commented on src/RestAPI/class-dlm-download-rest.php
> +			function ( $download ) {
nu era acelasi lucru daca faceai array_map($this->get_download_item, $fetch_downloads) ?

2024-07-08 13:59 UTC, cristeacosmin commented on vendor/composer/autoload_classmap.php
astea din vendor de ce sunt puse in git?

2024-07-16 14:09 UTC, razvanaldea89 commented on src/Admin/Admin.php
> +		wp_enqueue_script( 'jquery-blockui', download_monitor()->get_plugin_url() . '/assets/js/blockui.min.js', array( 'jquery' ), '2.61', true );
Legat de versiune, e versiunea 2.61 a jQuery blockUI plugin.

2024-07-16 14:28 UTC, razvanaldea89 commented on src/Admin/DownloadPaths/class-dlm-downloads-path-helper.php
> +		$saved_paths = self::get_all_paths();
Nu sunt probleme

2024-07-16 14:30 UTC, razvanaldea89 commented on src/Admin/DownloadPaths/class-dlm-downloads-path-table.php
> +		$selected_view = isset( $_REQUEST['view'] ) ? sanitize_text_field( wp_unslash( $_REQUEST['view'] ) ) : 'all';
Ne mai da erori WPCS-ul

2024-07-16 14:33 UTC, razvanaldea89 commented on src/Admin/DownloadPaths/class-dlm-downloads-path-table.php
> +	public function get_action_url( string $action, int $id, string $nonce_action = 'modify_approved_directories' )
Te referi la type? Daca da, l-am scos, imi mai punea editorul.

2024-07-16 14:33 UTC, cristeacosmin commented on src/Admin/DownloadPaths/class-dlm-downloads-path-helper.php
> +		$saved_paths = self::get_all_paths();
la asta ma refer: https://wiki.php.net/rfc/deprecate_partially_supported_callables

2024-07-17 06:28 UTC, razvanaldea89 commented on vendor/composer/autoload_classmap.php
nu inteleg

2024-07-17 07:43 UTC, cristeacosmin commented on src/Admin/Extensions.php
> +		echo wp_json_encode(array( 'message' => __( 'Plugin\'s license activated.', 'download-monitor' ) ) );
de ce ai facut modificarea asta? pentru ca pare ca wp_send_json_success e mai optim

2024-07-17 09:37 UTC, razvanaldea89 commented on src/Admin/Extensions.php
> +		echo wp_json_encode(array( 'message' => __( 'Plugin\'s license activated.', 'download-monitor' ) ) );
sa fie in ton cu restul clasei. o sa fac tichet sa inlocuim candva aceste echo-uri cu wp_send_json_

2024-08-09 10:51 UTC, cristeacosmin commented on src/Dependencies/PayPalHttp/HttpClient.php
> +	public $curlCls;
why camel case when everything seems to be snake_case?

2024-08-21 06:57 UTC, cristeacosmin approved these changes

2024-08-21 07:43 UTC, merged