[ #1565 ] - quick edit terms and conditions checkbox fix
WPChill/download-monitor pull request #1571
Opened 2024-10-15 11:36 UTC by razvanaldea89

2024-10-15 11:42 UTC, cristeacosmin requested changes

2024-10-15 11:42 UTC, cristeacosmin commented on assets/js/overview-download.js
> +            var terms_conditions = ('Yes' == $( '.column-locked_download span', $post_row ).data('_dlm_tc_locked') );
```suggestion
            var terms_conditions = ('Yes' === $( '.column-locked_download span', $post_row ).data('_dlm_tc_locked') );
```

2024-10-17 08:30 UTC, razvanaldea89 commented on assets/js/overview-download.js
> +            var terms_conditions = ('Yes' == $( '.column-locked_download span', $post_row ).data('_dlm_tc_locked') );
a8aa5f4a7310a7fb089ee0742a683afce7480226

2024-10-21 08:00 UTC, cristeacosmin approved these changes

2024-10-22 06:09 UTC, merged